### ISSUE TITLE
AES generation unable to create file

### ISSUE THREAD

**Issue by JoaoPere** [tsu-iscd/jcrypto#6]
Trying to run the example provided, the method generateAES() is not saving the correspondent WB-AES string to the designated file defined in Options.file. Used OS is Windows 10.

**Comment by dnkolegov** [comment]
Please provide steps to reproduce. 
Did you run tests with `grunt`?

**Comment by JoaoPere** [comment]
No, did not use `grunt`.

Installed JCrypto and Uglify-JS 2.7.4.using npm. Created a JS file with a similar content to the example:

```
var jcrypto = require('jcrypto');

var key = '0123456789abcdef0123456789abcdef';

var options = {  
    encoding: 'hex',
    wrapper: 'UMD',
    mangle: {  
        names: true,
        properties: true
   },
   file: __dirname + '\\aes.js'
};

console.log('Options file: ' + options.file);

// btw you can call it without options argument, default options described below
var res = jcrypto.generateAes(key, options);

console.log('AES generated');
console.log(res);

//options.file = '../hmac.js';
//jcrypto.generateHmac(key, options);
```

The code is generated and displayed in ` console.log(res);`. However, no file is created.

**Comment by dnkolegov** [comment]
Fixed via https://github.com/tsu-iscd/jcrypto/pull/7

**Comment by dnkolegov** [comment]
@JoaoPere:  Please verify.
